Codeforces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
app_name = "Codeforces"

urlpatterns = [
    path('',views.home,name="home"),
    # url(r'^(?P<name>[\w\-\.\@]+)/$', views.analysis, name='analysis'),
]

CodeforcesCrawler/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Codeforces.urls',namespace = "Codeforces")),
]

Codeforces/models.py
from django.db import models

# Create your models here.

Codeforces/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
import requests
import urllib.request
from html.parser import HTMLParser
from html.entities import name2codepoint
import time
from bs4 import BeautifulSoup
import lxml.html as lh
import pandas as pd
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
import requests
import urllib.request
from html.parser import HTMLParser
from html.entities import name2codepoint
import time
from bs4 import BeautifulSoup
import lxml.html as lh
import pandas as pd
from django.contrib.sites import requests
import requests, bs4, csv, json, time
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
import matplotlib
import numpy
import json
from django.urls import reverse
from collections import Counter

# Create your views here.
def home(request):

    if request.POST:
        if request.POST['handle']:
            url = 'https://codeforces.com/api/user.info?handles=' + str(request.POST['handle'])
            response = requests.get(url)
            name = str(request.POST['handle'])
            soup2 = bs4.BeautifulSoup(response.text, "html.parser")
            l2 = json.loads(str(soup2))
            if l2['status'] != 'OK':
                return render(request, 'home_page.html', {'flag': 1})
            else:
                url = 'https://codeforces.com/api/user.rating?handle=' + str(name)
                response = requests.get(url)
                soup2 = bs4.BeautifulSoup(response.text, "html.parser")
                l2 = json.loads(str(soup2))
                contest_count = len(l2['result'])
                col = []
                best_rank = 10000
                worst_rank = 0
                max_rating = 0
                lowest_rating = 10000
                current_rating = l2['result'][contest_count - 1]['newRating']
                rating_changes = []
                j = 1
                for t in l2['result']:
                    i = t['contestId']
                    d = t['rank']
                    c = t['contestName']
                    g = t['oldRating']
                    f = t['newRating']
                    e = f - g
                    h = 'https://codeforces.com/contest/' + str(i)
                    rating_changes.append(e)
                    best_rank = min(best_rank, d)
                    worst_rank = max(worst_rank, d)
                    max_rating = max(max_rating, f)
                    lowest_rating = min(lowest_rating, f)
                    col.append({'rank': d, 'con': c, 'change': e, 'new': f, 'old': g, 'link': h, 'count': j})
                    j += 1

                col.reverse()
                rating_changes.sort()
                max_up = rating_changes[len(rating_changes) - 1]
                max_down = rating_changes[0]
                max_down = min(0, max_down)

                # this is next comment which gives the submission history
                url1 = 'https://codeforces.com/api/user.status?handle=' + str(name) + '&from=1&count=10000'
                res = requests.get(url1)
                soup = bs4.BeautifulSoup(res.text, "html.parser")
                l = json.loads(str(soup))
                sub = []
                attempt = len(l['result'])  # attempts made by user
                attempted = set([])  # attempted questions
                solved_questions = set([])
                unsolved = set([])  # unsolved questions
                # different verdicts
                ac = 0
                tle = 0
                mle = 0
                ile = 0
                ce = 0
                re = 0
                wa = 0
                other = 0

                total_rating = list()
                solved_rating = list()
                final_rating_solved = list()
                problem_count = list()
                for i in range(50):
                    total_rating.append((i + 1) * 100)
                    solved_rating.append(0)

                languages = []
                indexes = []
                for item in l['result']:
                    if 'rating' in item['problem']:
                        cr = int(item['problem']['rating']) // 100
                        solved_rating[cr - 1] += 1

                    ask = str(item['problem']['contestId']) + '-' + str(item['problem']['index'])
                    asd = str(item['problem']['contestId']) + str(item['problem']['index']) + '-' + str(item['problem']['name'])
                    we = 'https://codeforces.com/problemset/problem/' + str(item['contestId']) + '/' + str(item['problem']['index'])
                    if item['verdict'] != "OK":
                        unsolved.add(we)

                    languages.append(item['programmingLanguage'])
                    indexes.append(item['problem']['index'][0])

                    attempted.add(asd)
                    if item['verdict'] == "OK":
                        solved_questions.add(we)
                        ac += 1
                    else:
                        if item['verdict'] == "WRONG_ANSWER":
                            wa += 1
                        else:
                            if item['verdict'] == "COMPILATION_ERROR":
                                ce += 1
                            else:
                                if item['verdict'] == "RUNTIME_ERROR":
                                    re += 1
                                else:
                                    if item['verdict'] == "TIME_LIMIT_EXCEEDED":
                                        tle += 1
                                    else:
                                        if item['verdict'] == "MEMORY_LIMIT_EXCEEDED":
                                            mle += 1
                                        else:
                                            if item['verdict'] == "IDLENESS_LIMIT_EXCEEDED":
                                                ile += 1
                                            else:
                                                other += 1

                series_for_lang = []
                cl = Counter(languages)
                for item in cl:
                    series_for_lang.append({
                        'name': item,
                        'y': cl[item]
                    })

                first_time_ac = 0
                for i in solved_questions:
                    if i in unsolved:
                        unsolved.remove(i)
                    else:
                        first_time_ac += 1
                unsolved_problems = list()
                for i in unsolved:
                    pr_name = str(i[42:])
                    my_pr_name = ""
                    for j in pr_name:
                        if j != '/':
                            my_pr_name += j
                        else:
                            my_pr_name += '-'
                    unsolved_problems.append({'link': i, 'name': my_pr_name})

                ic = Counter(indexes)
                ser_a = []
                ser_b = []
                for item in sorted(ic):
                    ser_a.append(item)
                    ser_b.append(ic[item])

                tried = len(attempted)
                accepted = len(attempted) - len(unsolved)

                for i in range(50):
                    if solved_rating[i] > 0:
                        final_rating_solved.append(total_rating[i])
                        problem_count.append(solved_rating[i])

                survived_series = {
                    'name': 'Solved',
                    'data': problem_count,
                    'color': 'black'
                }

                chart = {
                    'chart': {'type': 'column',
                              'plotBackgroundColor': 'green'},
                    'title': {'text': 'Rating wise problems solved'},
                    'xAxis': {'categories': final_rating_solved},
                    'series': [survived_series],
                    'credits': {
                        'enabled': False
                    }
                }

                dump = json.dumps(chart)

                chart2 = {
                    'chart': {'type': 'pie',
                              'plotBackgroundColor': 'red'},
                    'title': {'text': 'Attempts'},
                    'tooltip': {
                        'pointFormat': 'percentage : <b>{point.percentage:.1f}%</b>'
                    },
                    'series': [{
                        'name': 'verdicts',
                        'data': [
                            {
                                'name': 'Accepted(' + str(ac) + ')',
                                'y': ac
                            }, {
                                'name': 'Wrong Answer(' + str(wa) + ')',
                                'y': wa
                            }, {
                                'name': 'Compilation Error(' + str(ce) + ')',
                                'y': ce
                            }, {
                                'name': 'Runtime Error(' + str(re) + ')',
                                'y': re
                            }, {
                                'name': 'Memory limit Exceeded(' + str(mle) + ')',
                                'y': mle
                            }, {
                                'name': 'Time Limit Exceeded(' + str(tle) + ')',
                                'y': tle
                            }, {
                                'name': 'Idleness Limit Exceeded(' + str(ile) + ')',
                                'y': ile
                            }, {
                                'name': 'other(' + str(other) + ')',
                                'y': other
                            }
                        ]

Codeforces/templates/analysis.html
{% extends 'base.html' %}
{% load static %}
{% block T %} {{name}}{% endblock %}
{% block B %} 

{% block hed %}
<style type="text/css">
td
{
    padding:0 15px;
}
</style>
{% endblock %}

<div>
    <h1 align="center" style="font-size: 50px;color:red;">
     {{name}} 
</h1>

</div>

<br>
<br>
<br>
<div  class="col-5" style="float: left;margin-left: 200px;">
    
    <div class="ml-5 mr-5" >
        <h1 style="font-size: 30px;color:blue;margin-left: 50px;">
        Contests
    </h1>
    <br>
        <table class="mytables">
    
    <tr>
        <td>Rating</td>
        <td>{{current_rating}}</td>
    </tr>
    <tr>
        <td>Max Rating</td>
        <td>{{max_rating}}</td>
    </tr>
    <tr>
        <td>Lowest Rating</td>
        <td>{{lowest_rating}}</td>
    </tr>
    <tr>
        <td>No. of Contests</td>
        <td>{{contest_count}}</td>
    </tr>
    <tr>
        <td>Best Rank</td>
        <td>{{best_rank}}</td>
    </tr>
    <tr>
        <td>Worst Rank</td>
        <td>{{worst_rank}}</td>
    </tr>
    <tr>
        <td>Max Up</td>
        <td>{{max_up}}</td>
    </tr>
    <tr>
        <td>Max Down</td>
        <td>{{max_down}}</td>
    </tr>
</table>
    </div>
    
</div>


<div  class="col-5" style="float: right;padding-bottom: 80px;">
     <div class="ml-5 mr-5" >
    <h1 style="font-size: 30px;color:blue;">
        Submissions
    </h1>
    <table class="asdf">
        <br>
    <tr>
        <td>Submissions</td>
        <td>{{attempts}}</td>
    </tr>
    <tr>
        <td>Number of Problems Tried</td>
        <td>{{tried}}</td>
    </tr>
    <tr>
        <td>Problems Solved</td>
        <td>{{solved}}</td>
    </tr>
    <tr>
        <td>First Attempt Correct</td>
        <td>{{first_attempt_correct}}</td>
    </tr>
    <tr>
        <td>Average Submissions</td>
        <td>{{avg_sub}}</td>
    </tr>
</table>
</div>
</div>


<br>
<br>

<br>
<br>
<br>

<br>
<br>
<br>

<br>
<div class="container" align="center" style="margin-top: 100px;">
    <h1 style="font-size: 30px;color:blue;">
    Contests And Rating! {{contest_count}}
    </h1>
    <h3 style="font-size: 20px;color:purple;">
    No.of Contests :  {{contest_count}}
    </h3>
    <table class="contests">
    <tr>
        <th>index</th>
        <th>Contest Name</th>
        <th>Rank</th>
        <th>old rating</th>
        <th>new rating</th>
        <th>change</th>
    </tr>
    {% for t in c %}
    <tr>
        <td>{{t.count}}</td>
        <td><a href="{{t.link}}" target="_blank">{{t.con}}</a></td>
        <td>{{t.rank}}</td>
        <td>{{t.old}}</td>
        <td>{{t.new}}</td>
        <td>{{t.change}}</td>
    </tr>

    {% endfor %}

</table>
</div>

<br>
<br>
<br>
<br>
<br>

<div  class="unsolved" align="center" >
    <h1 style="font-size: 30px;color:blue;">Unsolved Questions</h1>
    {% for i in unsolved_problems %}
        <a href="{{i.link}}" target="_blank">{{i.name}}</a>
    {% endfor %}
    <br><br>
</div>



<br><br><br>



<br><br>
<div  align="center">
     <h1 style="font-size: 30px;color:blue;">Recent Submissions</h1>
    <table class="subs">
        <tr>
            <th>Submission ID</th>
            <th>Problem</th>
            <th>Language</th>
            <th>Verdict</th>
        </tr>
        {% for t in sub %}
            <tr>
                <td><a href="{{t.link }}" target="_blank">{{t.sub_id}}</a></td>
                <td><a href="{{t.link2}}" target="_blank">{{t.name}}</a></td>
                <td>{{t.lang}}</td>
                <td>{{t.verdict}}</td>
            </tr>
        {% endfor %}
    </table>
</div>




{% endblock %}

Codeforces/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block T     %} {% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'home.css' %}">
	{% block hed %} {% endblock %}
</head>
<body>
	{% block B %}{% endblock %}
</body>
</html>

Codeforces/templates/home_page.html
{% extends 'base.html' %}
{load static}

{% block T %}
CF Crawler
{% endblock %}

{% block B %}
<div class="container mt-5 ">
	<div class="jumbotron" style="background-color: lightblue;">
<h1 style="float: left;">
    THE CODEFORCES CRAWLER
</h1>
<form style="float: right;" method="post" action="{% url 'Codeforces:home' %}">
	{% csrf_token %}
	<label for="handle" >Search Codeforces Handle</label>
	<input type="text" name="handle"></input>
	{% if flag %}<h6 style="color:red;">Enter Correct Handle ! </h6>{% endif %}
</form>
</div>
</div>
<div class="container ">
	
<div class="jumbotron" style="background-color: lightblue;">
    <table>
        <tr>
            <th>
                Codeforces Contest
            </th>
            <th>
                Date and Time
            </th>
        </tr>
        {% for i in cfcontests %}
            <tr>
                <td>{{i.con}}</td>
                <td>{{i.time}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
<br>
<div class="jumbotron" style="background-color: lightblue;">
    <table>
        <tr>
            <th>
                Codechef Contest
            </th>
            <th>
               Date and Time
            </th>
        </tr>
        <tr>
            <td>{{c3}}</td>
            <td>{{t3}}</td>
        </tr>
        <tr>
            <td>{{c4}}</td>
            <td>{{t4}}</td>
        </tr>
    </table>
</div>
</div>

{% endblock %}